ci:
  - changed-files:
      - any-glob-to-any-file: .github/*
core:
  - changed-files:
      - any-glob-to-any-file: app/src/main/kotlin/*
dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/*.toml'
gradle:
  - changed-files:
      - any-glob-to-any-file: '**/build.gradle.kts'
hymnals:
  - changed-files:
      - any-glob-to-any-file: core/hymnal-content/impl/src/main/res/raw/*
l10n:
  - changed-files:
      - any-glob-to-any-file: foundation/l10n-strings/*
prefs:
  - changed-files:
      - any-glob-to-any-file: core/prefs/*
storage:
  - changed-files:
      - any-glob-to-any-file: core/storage/*
test:
  - changed-files:
      - any-glob-to-any-file: '**/src/test/**'