ci:
  - '.github/*'
core:
  - 'app/src/main/kotlin/*'
dependencies:
  - 'gradle/libs.versions.toml'
gradle:
  - all: ['*.gradle.kts', '*.gradle']
hymnals:
  - 'core/hymnal-content/impl/src/main/res/raw/*'
l10n:
  - 'foundation/l10n-strings/*'
layouts:
  - any: ['*.xml']
prefs:
  - 'core/prefs/*'
storage:
  - 'core/storage/*'
test:
  - any: ['*/src/test/*','*/src/androidTest/*']