name: Android CI

on:
  push:

jobs:
  testing:
    name: Lint and unit test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Decode Firebase google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
             echo $FIREBASE_CONFIG > app-v2/google-services.json

      - name: Decode Keystore properties file
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_STORE_PROPERTIES }}
        run: echo $KEY_PROPERTIES > app/keystore.properties

      - name: Run spotless
        run: ./gradlew spotlessCheck

      - name: Run Android lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
