name: Internal Release

on:
  push:
    branches:
      - temp-release

jobs:
  submit-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CIS_MIDIS_TOKEN }}

      - name: checkout submodules
        run: |
          git submodule init
          git submodule update

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Decode Firebase google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG > app/google-services.json
          echo $FIREBASE_CONFIG > app-v2/google-services.json

      - name: Decode Playstore key
        id: play_store_key
        uses: akiojin/decode-base64-github-action@v0.1.0
        with:
          base64: ${{ secrets.PLAY_KEY_BASE_64 }}
          output-path: secrets/play-account.json

      - name: Generate build number
        run: echo "BUILD_NUMBER=${{github.run_number}}" > distribution/build_number.properties

      - name: Build Release
        run: ./gradlew app:assembleRelease --stacktrace

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        id: build_signed
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Publish to Internal track
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: secrets/play-account.json
          packageName: com.tinashe.christInSong
          track: internal
          status: completed
          whatsNewDirectory: distribution/whatsnew
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          mappingFile: app/build/outputs/mapping/release/mapping.txt